### ISSUE TITLE
 ERROR  Invalid or unexpected token

### ISSUE THREAD

**Issue by kuainiao** [lyricat/mornin.fm#28]
yarn run v1.22.10
$ nuxt-ts

 ERROR  Invalid or unexpected token                                                                         13:40:25

  (function (exports, require, module, __filename, __dirname) { #!/usr/bin/env node
  ^

  SyntaxError: Invalid or unexpected token
  at new Script (vm.js:101:7)
  at createScript (vm.js:262:10)
  at Object.runInThisContext (vm.js:310:10)
  at wrapSafe (internal/modules/cjs/loader.js:967:15)
  at Module._compile (internal/modules/cjs/loader.js:1027:27)
  at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Object.require.extensions.<computed> [as .js] (node_modules/ts-node/src/index.ts:529:44)
  at Module.load (internal/modules/cjs/loader.js:928:32)
  at Function.Module._load (internal/modules/cjs/loader.js:769:14)
  at Module.require (internal/modules/cjs/loader.js:952:19)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by deanwong** [comment]
@kuainiao  just resolved 
please check https://github.com/lyricat/mornin.fm/pull/32

**Comment by kuainiao** [comment]
邮件已收到，谢谢！谢云飞
